config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  put 'admin/set_permission'

  resources :profiles, except: [:edit] do
    collection do
      get :edit
    end
    member do
      get :doctor
    end
  end
   
  devise_for :users, :skip => [:registrations] , :controllers => {:registartions => "users/registartions"}

  devise_scope :user do
    delete '/users' => "devise/registrations#destroy", :as => 'user_registration'
    get  'users/sign_up' => 'users/registrations#new'
    get  'users/:id/edit' => 'users/registrations#edit'
    
    get  'doctors/sign_up' => 'users/registrations#new_doctor', :as => 'new_doctor_registration'
    post 'doctors' => 'users/registrations#create', :as => 'doctor_registration'
    get 'doctors/edit' => 'users/registrations#edit_doctor', as: :edit_doctor_registration
    put 'doctors' => 'users/registrations#update'

    get  'patients/sign_up' => 'users/registrations#new_patient', :as => 'new_patient_registration'
    post 'patients' => 'users/registrations#create', :as => 'patient_registration'
    get  'patients/edit' => 'users/registrations#edit_patient', :as => 'edit_patient_registration'
    put  'patients' => 'users/registrations#update'
  end

  resources :payments, only: [:new, :index] do
    collection do
      get :access_setup
      post :transaction_fees
      put :initiate_payment
    end
  end

  root "pages#home"
  get "about" => "pages#about"
  get 'users/:id' => 'users#show'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  city       :string(255)
#  speciality :string(255)
#  created_at :datetime
#  updated_at :datetime
#  users_id   :string(255)
#  integer    :string(255)
#  user_id    :integer
#

class Profile < ActiveRecord::Base
  
  belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => '/images/:style/missing.png'

	validates :name, presence: true 
	validates :city, presence: true

  has_one :stripe_access_cred, through: :doctor_profile
  has_one :doctor_profile
  has_one :patient_profile
  accepts_nested_attributes_for :doctor_profile
  accepts_nested_attributes_for :patient_profile

  delegate :speciality, :gratuate_school, :degree, :professional_license,
           :year_of_completion, to: :doctor_profile, :prefix => true
  
  delegate :profile_type, to: :user, :prefix => true

  DOCTOR = 'doctor'
  PATIENT = 'patient'
  ADMIN = "admin"
  TYPES = [DOCTOR, PATIENT, ADMIN]

  # This method returns all doctor profiles
  def self.doctors
    self.joins(:user).where("users.profile_type = ?", DOCTOR)
  end
  
  def self.active
    self.joins(:doctor_profile).where("doctor_profiles.status = ?", true)
  end

  # this method filters the doctors by city, state , degree and speciality
  def self.search(search)
    if search
      doctors.joins(:doctor_profile).where('city LIKE ? OR state LIKE ? OR doctor_profiles.degree LIKE ?
                   OR doctor_profiles.speciality LIKE ? AND doctor_profiles.status = ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", true) 
    end
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :complete_profile_info, only: [:show, :index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :html, :xml, :json, :js

  # action returns list of all doctors , plus filterd doctors by city, state etc
  def index
    if params[:search]
      @profiles = Profile.search(params[:search])
      respond_to do |format|
        format.js 
      end  
    else
      @profiles = Profile.doctors.active
      respond_with(@profile)
    end
  end

  # Display doctor or patient profile
  def show
    @stripe_client_id = ENV['CLIENT_ID']
    respond_with(@profile)
  end

  # Render create new profile page. we need to remove this as we create blank user profile on user creation.
  def new
    if current_user.profile.nil?
      @profile = Profile.new 
      respond_with(@profile)
    else
      redirect_to profiles_path, notice: "You can only create one profile as a user"
    end
  end

  # To edit Doctor/Patient profile info. 
  def edit
    if current_user.is_doctor?
      @profile.build_doctor_profile unless @profile.doctor_profile
    else
      patient_profile = @profile.patient_profile || @profile.build_patient_profile 
      patient_profile.try(:allergy) || patient_profile.build_allergy
      patient_profile.try(:medication) || patient_profile.build_medication
      patient_profile.try(:previous_dignosed_condition) || patient_profile.build_previous_dignosed_condition
    end
  end

  # To create new profile,we don't need this too. will need to remove it.
  def create
    @profile = Profile.create({
        name: params['profile']['name'],
        speciality: params['profile']['speciality'],
        city: params['profile']['city'],
        user_id: current_user['id']
      })
    @profile.save
    respond_with(@profile)
  end

  # To update user profile.
  def update
    @profile.update(profile_params)
    respond_with(@profile)
  end

  # This is to destroy user profile. I think we don't need this as each user should have a profile.
  def destroy
    @profile.destroy
    respond_with(@profile)
  end

  def correct_user
    @profile = current_user.profile(id: params[:id])
    redirect_to profiles_path, notice: "Not authorized to edit this profile." if @profile.nil?
  end

  def doctor
    @profile = Profile.find(params[:id])
  end

  private

  def set_profile
    unless current_user
      @profile = Profile.find(params[:id])
    else 
      @profile = current_user.profile
    end
  end

  def profile_params
    if current_user.is_doctor?
      params.require(:profile).permit(:name, :city, :state, :image, doctor_profile_attributes: 
                          [:profile_id, :speciality, :year_of_completion, :gratuate_school, :degree, :professional_license])
    else
      params.require(:profile).permit(:name, :city, :state, :image, 
                                      patient_profile_attributes: [:profile_id, :gender,:date_of_birth, :location, 
                                      allergy_attributes: [:name, :note], medication_attributes: [:name, :note], 
                                      previous_dignosed_condition_attributes: [:name, :note] ])
    end
  end

  def complete_profile_info
    if current_user
      redirect_to edit_profiles_path, notice: "Please complete your profile first!." unless current_user.profile_completed? || current_user.is_admin?
    else
      redirect_to user_session_path, notice: "Please login before accessing doctors list!"
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end
end

app/views/profiles/_doctor_profile_fields.html.erb
<%= f.fields_for :doctor_profile do |doc| %>

  <div class="form-group col-sm-6">
    <%= doc.label :speciality  %><br>
    <%= doc.collection_select :speciality, DoctorProfile::SPECIALITY, :to_s, :to_s, {:include_blank => false}, {:class  => 'form-control'} %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :gratuate_school %><br>
    <%= doc.text_field :gratuate_school, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :degree %><br>
    <%= doc.collection_select :degree, DoctorProfile::DEGREES, :to_s, :to_s, {:include_blank => false}, {:class  => 'form-control'}  %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :professional_license %><br>
    <%= doc.text_field :professional_license, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :year_of_completion %><br>
    <%= doc.collection_select :year_of_completion, (1914..2014).to_a, :to_s, :to_s, {:include_blank => false}, {:class  => 'form-control'}  %>
  </div>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="dropdown">
    <%= f.label :speciality %><br>
    <%= f.text_field :speciality %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_patient_profile_fields.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>

<%= f.fields_for :patient_profile do |doc| %>
  <div class="form-group col-sm-6">
    <%= doc.label :gender  %><br>
    <%= doc.select(:gender, options_for_select([['Male', 'M'],['Female', 'F']], @profile.patient_profile.gender), {:include_blank => false}, {:class => "form-control"}) %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :date_of_birth %><br>
    <%= doc.date_select :date_of_birth, {:order => [:month, :day, :year],:prompt => true, :start_year => 1960, :end_year => Time.now.year}, :html=>{:class => "form-control"} %>
  </div>

  <div class="form-group col-sm-6">
    <%= doc.label :address %><br>
    <%= doc.text_field :location, :class => "form-control" %>
  </div>

  <%= doc.fields_for :Allergies do |a| %>
    <div class="form-group col-sm-6">
      <%= a.label :name, 'Allergies' %><br>
      <%= a.text_field :name, :class => "form-control" %>
      <%= a.label :note, 'Allergies Note' %><br>
      <%= a.text_area :note, class: "form-control" %>
    </div>
  <% end %>

  <%= doc.fields_for :medication do |m| %>
    <div class="form-group col-sm-6">
      <%= m.label :name, 'Medication' %><br>
      <%= m.text_field :name, :class => "form-control" %>
      <%= m.label :note, 'Medication Note' %><br>
      <%= m.text_area :note, :class => "form-control" %>
    </div>
  <% end %>

  <%= doc.fields_for :previous_dignosed_condition do |dc| %>
    <div class="form-group col-sm-6">
      <%= dc.label :name, 'Diagnosed Condition' %><br>
      <%= dc.text_field :name, :class => "form-control" %>
      <%= dc.label :note, 'Diagnosed Condition Note' %><br>
      <%= dc.text_area :note, :class => "form-control" %>
    </div>
  <% end %>

<% end %>

<script>
  $(function(){
	$("#profile_patient_profile_attributes_location	").geocomplete();
  });   
</script>

app/views/profiles/_profiles.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <h1>Your Doctors</h1>
    </div>
  </div>
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th>Name <br></th>
          <th>City <br></th>
          <th>State <br></th>
          <th>Degree <br></th>
          <th>Speciality <br></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td><%= profile.name %></td>
            <td><%= profile.city %></td>
            <td><%= profile.state %></td>
            <td><%= profile.doctor_profile.try(:degree) %></td>
            <td><%= profile.doctor_profile.try(:speciality) %></td>
            <td><%= link_to 'View Doctor Profile', doctor_profile_path(:id => profile) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/profiles/doctor.html.erb
<p id="notice"><%= notice %></p>
</br>
<% unless current_user ==  @profile.user%>
  <%= link_to 'Request to doctor', initiate_payment_payments_path(doctor_id: @profile), method: :put %>
<% end %>
<td class="round-image-20"><%= image_tag((current_user || @profile.user).avatar.url(:medium)) %></td>
<br>
<br>
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>
<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<div id="doctor">
  <p>
    <strong>Speciality:</strong>
    <%= @profile.doctor_profile_speciality %>
  </p>
  <p>
    <strong>Gratuate School:</strong>
    <%= @profile.doctor_profile_gratuate_school %>
  </p>
  <p>
    <strong>Degree:</strong>
    <%= @profile.doctor_profile_degree %>
  </p>

  <p>
    <strong>Graduated At:</strong>
    <%= @profile.doctor_profile_year_of_completion %>
  </p>

  <p>
    <strong>Professional License:</strong>
    <%= @profile.doctor_profile_professional_license %>
  </p>
</div>

app/views/profiles/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editing profile</h1>
	</div>
	<div class="panel-body">
	  <%= nested_form_for(@profile, :url => profile_path(@profile)) do |f| %>
      <% if @profile.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
          <% @profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group col-sm-6">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group col-sm-6">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>

      <div class="form-group col-sm-6">
        <%= f.label :state %><br>
        <%= select_tag 'State', options_for_select(us_states), :prompt =>"#{@profile.state}", :name=>"profile[state]", :id=>"state", class: "form-control"%> 
      </div>

        <%= render partial: current_user.profile_type.concat('_profile_fields'), locals: {:f => f} %>
      <br>
      <div class="form-group col-sm-12">
        <%= f.submit "Update", class: "btn btn-primary" %>
        <%= link_to 'Show', @profile %> |
        <%= link_to 'Back', profiles_path %>
      </div>
<% end %>

app/views/profiles/index.html.erb
<div class="panel-body">
  <%= form_tag profiles_path, :remote => true, :method => :get, :class => "form-search" do %>
    <div class="form-inline">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag "Search", :name => nil, class: "form-control" %>
    </div>    
  <% end %>
</div>

<div id="profiles"><%= render 'profiles' %></div>

app/views/profiles/index.js.erb
$('#profiles').html('<%= escape_javascript(render("profiles")) %>');

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<% if @profile.doctor_profile%>
  <h3>Doctor Profile's Info</h3>
<% else %> 
  <strong>Patient Profile's Info</strong>
<% end %>

<p id="notice"><%= notice %></p>
</br>

<td class="round-image-20"><%= image_tag((current_user || @profile.user).avatar.url(:medium)) %></td>
<br>
<br>
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>
<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>
<% if current_user || ( @profile || current_user.is_doctor? ) %>
  <% if @profile.doctor_profile%>
    <div id="doctor">
      <p>
        <strong>Speciality:</strong>
        <%= @profile.doctor_profile_speciality %>
      </p>
      <p>
        <strong>Gratuate School:</strong>
        <%= @profile.doctor_profile_gratuate_school %>
      </p>
      <p>
        <strong>Degree:</strong>
        <%= @profile.doctor_profile_degree %>
      </p>

      <p>
        <strong>Graduated At:</strong>
        <%= @profile.doctor_profile_year_of_completion %>
      </p>

      <p>
        <strong>Professional License:</strong>
        <%= @profile.doctor_profile_professional_license %>
      </p>
    </div>
  <% end %>
<% end %>
<% if current_user || ( @profile || current_user.is_patient? ) %>
	<% if @profile.patient_profile%>
    <p>
      <strong>Gender:</strong>
      <%= @profile.patient_profile.gender %>
    </p>
    
    <p>
      <strong>Date of Birth:</strong>
      <%= date_format(@profile.try(:patient_profile).try(:date_of_birth)) %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @profile.patient_profile.location %>
    </p>
  <% end %>
<% end %>
<% if @profile.user == current_user %>
  <%= link_to 'Edit', edit_profiles_path %> |
<% end %>
<%= link_to 'Back', profiles_path %>