config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  put 'admin/set_permission'

  resources :profiles, except: [:edit] do
    collection do
      get :edit
    end
    member do
      get :doctor
    end
  end
   
  devise_for :users, :skip => [:registrations] , :controllers => {:registartions => "users/registartions"}

  devise_scope :user do
    delete '/users' => "devise/registrations#destroy", :as => 'user_registration'
    get  'users/sign_up' => 'users/registrations#new'
    get  'users/:id/edit' => 'users/registrations#edit'
    
    get  'doctors/sign_up' => 'users/registrations#new_doctor', :as => 'new_doctor_registration'
    post 'doctors' => 'users/registrations#create', :as => 'doctor_registration'
    get 'doctors/edit' => 'users/registrations#edit_doctor', as: :edit_doctor_registration
    put 'doctors' => 'users/registrations#update'

    get  'patients/sign_up' => 'users/registrations#new_patient', :as => 'new_patient_registration'
    post 'patients' => 'users/registrations#create', :as => 'patient_registration'
    get  'patients/edit' => 'users/registrations#edit_patient', :as => 'edit_patient_registration'
    put  'patients' => 'users/registrations#update'
  end

  resources :payments, only: [:new, :index] do
    collection do
      get :access_setup
      post :transaction_fees
      put :initiate_payment
    end
  end

  root "pages#home"
  get "about" => "pages#about"
  get 'users/:id' => 'users#show'

end

app/views/pages/about.html.erb
<div class="jumbotron">
<h1>About Us</h1>
<p> At EirMD we understand that a visit to the doctor's office can be a time-consuming and stressful experience. Between work schedules, children, and endless other obligations- a simple checkup generally results in most of your day spent in a waiting room. EirMD wants to bring the doctors to you. We believe house calls save valuable time, reduce the chance of catching illnesses from other patients, and provide a compassionate experience within the comfort of your own home. 

EirMD employs a team of board-certified medical practitioners, nurses, and physicians throughout the country. Simply pull up the website, explain a few of your symptoms, and EirMD will send over the doctor of your choice to take care of the checkup. Let's cut out the waiting room.</p></div>

app/views/pages/home.html.erb
<div class= center>
	<h1>Welcome to EirMD</h1>
	<div class="table">
		<div class="col-sm-6 col-md-6 left">
			<div class="thumbnail">
				<%= image_tag("http://prestigefamilydentistry.com/wp-content/uploads/2012/08/Stock-Smile-03.png", :alt => "rss feed") %>
				<div class="caption">
					<% unless user_signed_in? %>
						<h3>New Patients</h3>
						<p>Stuck at home? Just need a check up? Sign up here!</p>
						<p><%=link_to " New Patients Click Here!",new_patient_registration_path, class: "btn btn-primary btn-lg"%></p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="table">
		<div class="col-sm-6 col-md-6 right">
			<div class="thumbnail">
				<%= image_tag("http://www.benin2009.com/file/2014/06/a-few-helpful-doctors-ready-to-excuse-you.jpg", :alt => "rss feed") %>
				<div class="caption">
					<% unless user_signed_in? %>
						<h3>Healthcare Professionals</h3>
						<p>Looking to grow your practice? Try something new?</p>
						<p><%=link_to " Start your Practice!",new_doctor_registration_path, class: "btn btn-primary btn-lg"%></p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>