config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  put 'admin/set_permission'

  resources :profiles, except: [:edit] do
    collection do
      get :edit
    end
    member do
      get :doctor
    end
  end
   
  devise_for :users, :skip => [:registrations] , :controllers => {:registartions => "users/registartions"}

  devise_scope :user do
    delete '/users' => "devise/registrations#destroy", :as => 'user_registration'
    get  'users/sign_up' => 'users/registrations#new'
    get  'users/:id/edit' => 'users/registrations#edit'
    
    get  'doctors/sign_up' => 'users/registrations#new_doctor', :as => 'new_doctor_registration'
    post 'doctors' => 'users/registrations#create', :as => 'doctor_registration'
    get 'doctors/edit' => 'users/registrations#edit_doctor', as: :edit_doctor_registration
    put 'doctors' => 'users/registrations#update'

    get  'patients/sign_up' => 'users/registrations#new_patient', :as => 'new_patient_registration'
    post 'patients' => 'users/registrations#create', :as => 'patient_registration'
    get  'patients/edit' => 'users/registrations#edit_patient', :as => 'edit_patient_registration'
    put  'patients' => 'users/registrations#update'
  end

  resources :payments, only: [:new, :index] do
    collection do
      get :access_setup
      post :transaction_fees
      put :initiate_payment
    end
  end

  root "pages#home"
  get "about" => "pages#about"
  get 'users/:id' => 'users#show'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :authenticate_user!

  def new
    @payment = Payment.new
  end

  def index
    if current_user.is_doctor?
      @stripe_client_id = ENV['CLIENT_ID']
      @pendind_permissions = current_user.try(:profile).try(:doctor_profile).stripe_access_creds.where(:access_token => nil)
      @received_payments = current_user.try(:profile).try(:doctor_profile).stripe_access_creds.where(:paid => true)
      @pending_payments = current_user.try(:profile).try(:doctor_profile).stripe_access_creds.where("access_token IS NOT NULL")
      render 'doctors_payment'
    elsif current_user.is_patient?
      @ready_for_payments = current_user.stripe_access_creds.where("access_token IS NOT NULL AND paid =?", false)
      @paid_payments = current_user.stripe_access_creds.where(:paid => true)
      render 'patients_payment'
    end
  end

  def initiate_payment
    profile = Profile.find(params[:doctor_id])
    StripeAccessCred.create(:doctor_profile_id => profile.doctor_profile.id, :patient_id => current_user.id )
    redirect_to payments_path, :notice => 'Have send request!'
  end

  def access_setup
	  access_cred = StripeAccessCred.where(id: params['state']).first
	  access_cred.access_token = params['code']
	  if access_cred.save
			flash[:notice] = "You have completed your account setting!"
	  else
			flash[:notice] = "You have completed your account setting!"
	  end
	  redirect_to profile_path(current_user.profile)
  end

  def transaction_fees
		# Get the credit card details submitted by the form
		token = params[:payment][:stripe_card_token]

		# This fetches payment code
		payment_info = StripeAccessCred.where(:id => params[:payment_id]).first

		if payment_info
			begin
				response = HTTParty.post("https://connect.stripe.com/oauth/token?client_secret=#{ENV['CLIENT_SECRET']}&code=#{payment_info.access_token}&grant_type=authorization_code")
				unless response['error']
					# Create the charge on Stripe's servers - this will charge the user's card
					charge = Stripe::Charge.create({
							:amount => 1000,
							:currency => "usd",
							:card => token,
							:description => "payinguser@example.com",
							:application_fee => 23},
							response['access_token']
						)
					if charge.paid
            payment_info.paid = true
            payment_info.save!
        		flash[:notice] = "Fee successfully submitted!"
        	else
						flash[:error] = charge.failure_message
					end
				else
					flash[:error] = response['error_description']
				end
			rescue Exception => e
				# Need to manage a log file for this
				flash[:error] = "Something went wrong!"
			end
		else
			flash[:error] = "Doctor's stripe info is not setup!"
		end
    redirect_to payments_path
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/doctors_payment.html.erb
<h1> Made permissions for new payments: </h1>
<% @pendind_permissions.each do |payment|%>
  <div>
    <%= link_to "Permit  to pay",       "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=#{@stripe_client_id}&scope=read_write&state=#{payment.id}" %> to <%= payment.try(:patient).try(:profile).try(:name) %>
  </div>
  <br>
<% end %>

<h1> Received Payments:  </h1>

<% @received_payments.each do |payment|%>
  <div>
    Made By: <%= payment.try(:patient).try(:profile).try(:name) %>
  </div>
  <br>
<% end %>

<h1></h1>

<% @pending_payments.each do |payment|%>
  <div>
    From: <%= payment.try(:patient).try(:profile).try(:name) %>
  </div>
  <br>
<% end %>

app/views/payments/new.html.erb
<%= form_for @payment, url: transaction_fees_payments_path do |f| %>
  <%= f.hidden_field :stripe_card_token %>

  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>

  <%= hidden_field_tag :payment_id, params[:payment_id] %>

  <div class="field">
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
  <div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <%= f.submit "Pay Fees" %>
<% end %>

<script type="text/javascript">
  jQuery(function() {
    var payment;

    payment = {
      setupForm: function() {
        return $('#new_payment').submit(function() {
          $('input[type=submit]').attr('disabled', true);
          if ($('#card_number').length) {
            payment.processCard();
            return false;
          } else {
            return true;
          }
        });
      },
      processCard: function() {
        var card;
        card = {
          number: $('#card_number').val(),
          cvc: $('#card_code').val(),
          expMonth: $('#card_month').val(),
          expYear: $('#card_year').val()
        };
        return Stripe.createToken(card, payment.handleStripeResponse);
      },
      handleStripeResponse: function(status, response) {
        if (status === 200) {
          $('#payment_stripe_card_token').val(response.id);
          return $('#new_payment')[0].submit();
        } else {
          $('#stripe_error').text(response.error.message);
          return $('input[type=submit]').attr('disabled', false);
        }
      }
    };

    Stripe.setPublishableKey($('meta[name="stripe-key"]').attr('content'));
    return payment.setupForm();
  });

</script>

app/views/payments/patients_payment.html.erb
<h1> Payments to make: </h1>
<% @ready_for_payments.each do |payment|%>
  <div>
    <%= link_to "Make payment to #{payment.try(:doctor_profile).try(:profile).try(:name)}", new_payment_path(:payment_id => payment.id)  %>
  </div>
<% end %>

<h1> Paid payments: </h1>

<% @paid_payments.each do |payment|%>
  <div>
    Made To: <%= payment.try(:doctor_profile).try(:profile).try(:name) %>
  </div>
<% end %>