config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  put 'admin/set_permission'

  resources :profiles, except: [:edit] do
    collection do
      get :edit
    end
    member do
      get :doctor
    end
  end
   
  devise_for :users, :skip => [:registrations] , :controllers => {:registartions => "users/registartions"}

  devise_scope :user do
    delete '/users' => "devise/registrations#destroy", :as => 'user_registration'
    get  'users/sign_up' => 'users/registrations#new'
    get  'users/:id/edit' => 'users/registrations#edit'
    
    get  'doctors/sign_up' => 'users/registrations#new_doctor', :as => 'new_doctor_registration'
    post 'doctors' => 'users/registrations#create', :as => 'doctor_registration'
    get 'doctors/edit' => 'users/registrations#edit_doctor', as: :edit_doctor_registration
    put 'doctors' => 'users/registrations#update'

    get  'patients/sign_up' => 'users/registrations#new_patient', :as => 'new_patient_registration'
    post 'patients' => 'users/registrations#create', :as => 'patient_registration'
    get  'patients/edit' => 'users/registrations#edit_patient', :as => 'edit_patient_registration'
    put  'patients' => 'users/registrations#update'
  end

  resources :payments, only: [:new, :index] do
    collection do
      get :access_setup
      post :transaction_fees
      put :initiate_payment
    end
  end

  root "pages#home"
  get "about" => "pages#about"
  get 'users/:id' => 'users#show'

end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "EirMD", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to 'Home', root_path%></li>
        <li><%=link_to 'About', about_path%></li>
        <li><%=link_to 'Doctors', profiles_path%></li>
          <% if user_signed_in? %>
            <% if current_user.is_admin? %>
              <li><%= link_to "Authorize Doctors", admin_index_path %></li>
            <% else %>
              <li><%= link_to "Payment Info", payments_path %></li>
              <li><%= link_to "Profile", profile_path(current_user) %></li>
              <% if current_user.is_patient? %>
                <li><%= link_to "Account Settings", edit_patient_registration_path %></li>
              <% else %>
                <li><%= link_to "Account Settings", edit_doctor_registration_path %></li>
              <% end %>
            <% end %>
            <li><%=link_to 'Log Out', destroy_user_session_path, method: :delete %>
            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
          <% else %>
            <li><%=link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EirMD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial scale=1.0'>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class='container'>
    <div id="flash">
      <%= render :partial => 'layouts/flash'%>
    </div>
	<%= yield %>
	</div>
</body>
</html>